// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvtrYUIBZO0ouvONibc8IDDdkuMNlXjXY',
    appId: '1:582280825311:web:b3a7b573f300f59ecb9c6a',
    messagingSenderId: '582280825311',
    projectId: 'chatapp-tutorial-3a676',
    authDomain: 'chatapp-tutorial-3a676.firebaseapp.com',
    storageBucket: 'chatapp-tutorial-3a676.appspot.com',
    measurementId: 'G-PZRWLNB1KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgvZ7Sm3AYEjzM48Wjs8hehYNriJ2od_0',
    appId: '1:582280825311:android:13407aae3bdcec3dcb9c6a',
    messagingSenderId: '582280825311',
    projectId: 'chatapp-tutorial-3a676',
    storageBucket: 'chatapp-tutorial-3a676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfY3nj-4Gs0f5A3uVdBWbYPBzjcoPh22A',
    appId: '1:582280825311:ios:b210ee516c8f890fcb9c6a',
    messagingSenderId: '582280825311',
    projectId: 'chatapp-tutorial-3a676',
    storageBucket: 'chatapp-tutorial-3a676.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfY3nj-4Gs0f5A3uVdBWbYPBzjcoPh22A',
    appId: '1:582280825311:ios:b210ee516c8f890fcb9c6a',
    messagingSenderId: '582280825311',
    projectId: 'chatapp-tutorial-3a676',
    storageBucket: 'chatapp-tutorial-3a676.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvtrYUIBZO0ouvONibc8IDDdkuMNlXjXY',
    appId: '1:582280825311:web:4a8528a954e65479cb9c6a',
    messagingSenderId: '582280825311',
    projectId: 'chatapp-tutorial-3a676',
    authDomain: 'chatapp-tutorial-3a676.firebaseapp.com',
    storageBucket: 'chatapp-tutorial-3a676.appspot.com',
    measurementId: 'G-F818J8P45J',
  );
}
